Document: volk
Title: Debian volk Manual
Author: <insert document author here>
Abstract: This manual describes what volk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/volk/volk.sgml.gz

Format: postscript
Files: /usr/share/doc/volk/volk.ps.gz

Format: text
Files: /usr/share/doc/volk/volk.text.gz

Format: HTML
Index: /usr/share/doc/volk/html/index.html
Files: /usr/share/doc/volk/html/*.html
